---
name: build-test-pull-request

on:
  push:
    branches:
      - trying
      - staging
  pull_request:
    branches:
      - '*'
jobs:
  build-riotdocker-base:
    name: Build and test pull request
    runs-on: ubuntu-latest
    env:
      RIOT_BRANCH: '2020.10'

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache riotdocker-base layer
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-base
          key: ${{ runner.os }}-buildx-base-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-base-

      - name: Build and push riotdocker-base
        uses: docker/build-push-action@v2
        with:
          context: ./riotdocker-base
          platforms: linux/amd64
          load: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/riotdocker-base:latest
          cache-from: type=local,src=/tmp/.buildx-cache-base
          cache-to: type=local,dest=/tmp/.buildx-cache-base-new

      - name: Move cache
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        run: |
          rm -rf /tmp/.buildx-cache-base
          mv /tmp/.buildx-cache-base-new /tmp/.buildx-cache-base

      - name: Cache static-test-tools
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-static
          key: ${{ runner.os }}-buildx-static-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-static-

      - name: Build static-test-tools
        uses: docker/build-push-action@v2
        with:
          context: ./static-test-tools
          platforms: linux/amd64
          load: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/static-test-tools:latest
          build-args: |
            DOCKERHUB_REGISTRY=${{ secrets.DOCKERHUB_USERNAME }}
          cache-from: type=local,src=/tmp/.buildx-cache-static
          cache-to: type=local,dest=/tmp/.buildx-cache-static-new

      - name: Move cache
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        run: |
          rm -rf /tmp/.buildx-cache-static
          mv /tmp/.buildx-cache-static-new /tmp/.buildx-cache-static

      - name: Cache riotbuild
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-riotbuild
          key: ${{ runner.os }}-buildx-riotbuild-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-riotbuild-

      - name: Build riotbuild
        uses: docker/build-push-action@v2
        with:
          context: ./riotbuild
          platforms: linux/amd64
          load: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/riotbuild:latest
          build-args: |
            DOCKERHUB_REGISTRY=${{ secrets.DOCKERHUB_USERNAME }}
          cache-from: type=local,src=/tmp/.buildx-cache-riotbuild
          cache-to: type=local,dest=/tmp/.buildx-cache-riotbuild-new

      - name: Move cache
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        run: |
          rm -rf /tmp/.buildx-cache-riotbuild
          mv /tmp/.buildx-cache-riotbuild-new /tmp/.buildx-cache-riotbuild

      - name: Checkout RIOT
        uses: actions/checkout@v2
        with:
          repository: RIOT-OS/RIOT
          ref: ${{ env.RIOT_BRANCH }}-branch
          path: RIOT

      - name: Run gnu build test
        run: |
          make -CRIOT/examples/hello-world buildtest
        env:
          BUILD_IN_DOCKER: 1
          DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/riotbuild:latest
          BOARDS: "arduino-uno esp32-wroom-32 hifive1 msb-430h native pic32-wifire samr21-xpro"

      - name: Run llvm build test
        run: |
          make -CRIOT/examples/hello-world buildtest
        env:
          TOOLCHAIN: llvm
          BUILD_IN_DOCKER: 1
          DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/riotbuild:latest
          BOARDS: "native samr21-xpro"

      - name: Run static tests
        run: |
          docker run --rm -t -v $(pwd)/RIOT:/data/riotbuild \
          -e CI_BASE_BRANCH=${{ env.RIOT_BRANCH }}-branch ${{ secrets.DOCKERHUB_USERNAME }}/riotbuild:latest \
          ./dist/tools/ci/static_tests.sh
